services:
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8998:8998"
      - "8999:8999"
      - "6499:6499"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/finance-management-api-dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finance-management-api-dev-network
    command: sh -c "sleep 5 && bun run db:migrate && bun run dev"

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=finance-management-api-dev
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - finance-management-api-dev-network
    ports:
      - "5432:5432"
    healthcheck: # Add health check
      test: [CMD-SHELL, pg_isready -U root -d finance-management-api-dev]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  finance-management-api-dev-network:
    driver: bridge

volumes:
  postgres-data-dev:
