services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=finance-management-api
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - finance-management-api-network
    ports:
      - "5432:5432"

networks:
  finance-management-api-network:
    driver: bridge

volumes:
  postgres-data:
