services:
  api:
    build:
      context: .
      target: release
    ports:
      - "8998:8998"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    networks:
      - finance-management-api-network

networks:
  finance-management-api-network:
    driver: bridge

volumes:
  postgres-data:
