name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Thanks for opening your first issue! We value your feedback and will look into this soon. Please make sure you've included all relevant details to help us understand the problem better."
        pr-message: "🎉 Thanks for opening your first pull request! We really appreciate your contribution to making this project better. We'll review your changes and get back to you soon."
